[[items]]
name = "Milk"
alternative_names = [
    "Cow's Milk",
    "Dairy Milk"
]
state = "carnist"
description = """
Given the chance, cows nurture their young and form lifelong friendships with one another.
They play games and have a wide range of emotions and personality traits.
But most cows raised for the dairy industry are intensively confined,
leaving them unable to fulfill their most basic desires, such as nursing their calves, even for a single day.
They are treated like milk-producing machines and are genetically manipulated and may be pumped full of antibiotics and hormones in order to produce more milk.
While cows suffer on factory farms, humans who drink their milk increase their chances of developing heart disease, diabetes, cancer, and many other ailments.
"""
sources = [
    { type = "url", value = "https://www.peta.org/issues/animals-used-for-food/animals-used-food-factsheets/cows-milk-cruel-unhealthy-product/" }
]
vegan_alternatives = ["Oat Milk", "Soy Milk", "Rice Milk", "Cashew Milk", "Almond Milk", "Coconut Drink"]

[[items]]
name = "Oat Milk"
alternative_names = []
state = "vegan"
description = """
Oat milk is a type of plant milk derived from whole oat grains by soaking the plant material to extract its nutrients.
Oat milk naturally has a creamy texture and a characteristically oatmeal-like flavor, though it is sold commercially in various flavor-varieties such as sweetened, unsweetened, vanilla, and chocolate.
Unlike other plant milks, whose origins date as early as the 13th century, oat milk is a modern creation, developed by the Swedish scientist Rickard Oste in the early 1990s,
who went on to found Oatly, the first commercial manufacturer of oat milk."""
sources = [
    { type = "url", value = "https://en.wikipedia.org/wiki/Oat_milk" },
    { type = "url", value = "https://www.oatly.com/int/the-oatly-way" }
]
vegan_alternatives = []

[[items]]
name = "Casein"
alternative_names = []
state = "carnist"
description = """
A family of proteins found in dairy milk resposible the strechiness typically associated with melted cheese.
"""
sources = [
    { type = "url", value = "https://www.vegan.com/casein/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Casein" },
    { type = "url", value = "https://itdoesnttastelikechicken.com/melty-stretchy-gooey-vegan-mozarella/" }
]
vegan_alternatives = ["Tapioca Starch"]

[[items]]
name = "Whey"
alternative_names = []
state = "carnist"
description = """
The liquid that remains after dairy milk has been curdled and strained.
A by-product of the cheese industry found in surprisingly many otherwise vegan foods.
Often found in protein shakes.
"""
sources = [
    { type = "url", value = "https://www.vegan.com/whey/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Whey" },
    { type = "url", value = "https://www.bodybuilding.com/fun/10-best-tasting-vegan-protein-powders.html" }
]
vegan_alternatives = ["Pea Protein", "Rice Protein"]

[[items]]
name = "Lactose"
alternative_names = [
    "Milk sugar"
]
state = "carnist"
description = """
A sugar found in dairy milk. About 65% of the global population are lactose intolerant,
which pushes the market to produce a wide variety of dairy-free products.
"""
sources = [
    { type = "url", value = "https://www.vegan.com/dairy-free/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Lactose" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Lactose_intolerance" }
]
vegan_alternatives = []
